/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZEEIzqRShg6
 */
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";

export function LeaderBoardTable() {
  const leaderBoardArray = [
    {
      title: "Introduction to Web Development",
      id: 1,
    },
    {
      title: "Mastering Tailwind CSS Framework",
      id: 2,
    },
    {
      title: "Building Scalable Web Applications",
      id: 3,
    },
  ];

  return (
    <Table className="max-w-[43rem] text-white bg-white">
      <TableHeader>
        <TableRow>
          <TableHead className="justify-start">ID</TableHead>
          <TableHead className="justify-center">Title</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {leaderBoardArray.map((item) => (
          <TableRow key={item.id}>
            <TableCell className="font-medium">{item.id}</TableCell>
            <TableCell className="justify-center">{item.title}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
